name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        version: ["1312.3", "1443.0", "today"]
    steps:
    - uses: actions/checkout@v4
    # Workaround for https://github.com/actions/runner-images/issues/9425, to be removed once the issue is resolved
    - name: patch crun (Workaround for https://github.com/actions/runner-images/issues/9425)
      run: |
        tmpdir="$(mktemp -d)"
        pushd "$tmpdir"

        curl -Lo ./crun https://github.com/containers/crun/releases/download/1.14.3/crun-1.14.3-linux-amd64
        GOOD_SHA=80c5ab9422d4672f650f2bad3da933568349b64117d055486abc3534517be2af

        sha256sum ./crun
        OUR_SHA=$(sha256sum ./crun | awk '{ print $1 }')

        if [[ "$GOOD_SHA" == "$OUR_SHA" ]]; then
            sudo install crun /usr/bin/crun
        else
            echo "Checksums do not match"
            exit 1
        fi
        popd
        rm -rf "$tmpdir"
      shell: bash
    - name: Show crun version after the patch
      shell: bash
      run: |
        crun --version
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Build
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        if [[ ${{ matrix.version }} == today ]]; then
          git clone --depth=1 https://github.com/gardenlinux/gardenlinux
        else
          git clone --depth=1 --branch=${{ matrix.version }} https://github.com/gardenlinux/gardenlinux
        fi
        cd gardenlinux
        if [[ ${{ matrix.version }} == today ]]; then
          echo no need to change version
        else
          echo ${{ matrix.version }} > VERSION
          git commit -am "Version ${{ matrix.version }}"
        fi
        ./build kvm_curl-lima-${{ matrix.arch }}
    - uses: actions/upload-artifact@v4
      with:
        name: gl-lima-${{ matrix.version }}-${{ matrix.arch }}
        path: gardenlinux/.build/*qcow2
