name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        git clone --depth=1 https://github.com/gardenlinux/gardenlinux
        cd gardenlinux
        ./build kvm-lima
    - uses: actions/upload-artifact@v4
      with:
        name: gl-lima
        path: gardenlinux/.build/*qcow2
