name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    # Workaround for https://github.com/actions/runner-images/issues/9425, to be removed once the issue is resolved
    - name: patch crun (Workaround for https://github.com/actions/runner-images/issues/9425)
      run: |
        tmpdir="$(mktemp -d)"
        pushd "$tmpdir"

        curl -Lo ./crun https://github.com/containers/crun/releases/download/1.14.3/crun-1.14.3-linux-amd64
        GOOD_SHA=80c5ab9422d4672f650f2bad3da933568349b64117d055486abc3534517be2af

        sha256sum ./crun
        OUR_SHA=$(sha256sum ./crun | awk '{ print $1 }')

        if [[ "$GOOD_SHA" == "$OUR_SHA" ]]; then
            sudo install crun /usr/bin/crun
        else
            echo "Checksums do not match"
            exit 1
        fi
        popd
        rm -rf "$tmpdir"
      shell: bash
    - name: Show crun version after the patch
      shell: bash
      run: |
        crun --version
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Build
      run: |
        git clone --depth=1 --branch=1443.0 https://github.com/gardenlinux/gardenlinux
        cd gardenlinux
        ./build kvm_curl-${{ matrix.arch }}
    - uses: actions/upload-artifact@v4
      with:
        name: gl-qemu-${{ matrix.arch }}
        path: gardenlinux/.build/*raw
